### ISSUE TITLE
release 2.1.0 does not actually contain the latest update 

### ISSUE THREAD

**Issue by inanc-g** [muxinc/strapi-plugin-mux-video-uploader#25]
@erikpena 

PR #22 adds support for strapi v4, but the latest release 2.1.0 (both on GitHub and npm) is still identical to 2.0.0:
 - release on GitHub: https://github.com/muxinc/strapi-plugin-mux-video-uploader/releases/tag/v2.1.0
 - notice that the diff between 2.0.0 and 2.1.0 does not contain any changes apart from the version number: https://github.com/muxinc/strapi-plugin-mux-video-uploader/compare/v2.0.0...v2.1.0
 - if you download the source code assets from the GitHub release, notice that the source is also identical to 2.0.0
 - same if installed via npm

If you add the package directly from github (f.e., via `npm i git+https://github.com/muxinc/strapi-plugin-mux-video-uploader.git`), then the package will actually contain the latest source. 
Unfortunately, for me, using strapi v4.0.7 community edition, the plugin does not show up in the admin panel (even after clearing cache / build folders & rebuilding). It seems to me that the plugin is not registered correctly, as it also does not show up in the list of plugins.

Also note that the docs on https://docs.mux.com/guides/video/integrate-with-strapi should be updated for v4 support.

**Comment by erikpena** [comment]
Hey @inanc-g, thank you very much for the callout.  It turns out that there was an issue with how we published the release.  Take a look at v2.1.1 which should _actually_ contain the necessary bits for v4 support.  So installing it should get you what you are looking for.

Additionally, and this applies to other Strapi plugins in general— if you install locally, you need to "enable" the plugin (Step 5 of https://docs.strapi.io/developer-docs/latest/development/plugins-development.html#creating-a-plugin).

As part of this release, we also had updated our documentation and it was making it's paces to being published.  Which it is now :-).  Feel free to take a look at the url you provided now.
