### ISSUE TITLE
Cant upload any video from my Macbook - Have file issue

### ISSUE THREAD

**Issue by hani-nguyen-eh** [muxinc/strapi-plugin-mux-video-uploader#88]
Link demo bellow

https://github.com/user-attachments/assets/4b0d0751-d7db-48ed-9c46-4de1d5ab085c

**Comment by erikpena** [comment]
Hello @hani-nguyen-eh,
Thank you for submitting this.  Can you do a couple of things for me:

- Provide the HAR capture from your browser's DevTools (https://support.google.com/admanager/answer/10358597?hl=en) and provide the HAR by sending this to support@mux.com (Mention me, Erik Pena, so that it gets routed to me).  Emailing is preferred given the cookie and session details that will be too sensitive to send on github.
- In your instance of Strapi, can you capture the STDOUT (console) and send that as well?

Thank you,

**Comment by erikpena** [comment]
Thank you @hani-nguyen-eh for creating the Support ticket.  I'll be working with you on that and will report back here with what the findings are to benefit others that might be running into the same issue.
